# Generated by Django 3.2.13 on 2022-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
